
// If the database is empty on server start, create a collection to store icon paths and data
Meteor.startup(function () {
    if (CategoryIcons.find().count() === 0) {
        var data = [
            {name: "Allergy_Vials",     image: 'icons/Allergy_Vials.png'},
            {name: "Ambulance",     image: 'icons/Ambulance.png'},
            {name: "Baby_Bottle",     image: 'icons/Baby_Bottle.png'},
            {name: "Baby_Carriage",     image: 'icons/Baby_Carriage.png'},
            {name: "Bacteria",     image: 'icons/Bacteria.png'},
            {name: "Band_Aid",     image: 'icons/Band_Aid.png'},
            {name: "Bandage_Roll",     image: 'icons/Bandage_Roll.png'},
            {name: "Blood_Bag",     image: 'icons/Blood_Bag.png'},
            {name: "Blood_Pressure",     image: 'icons/Blood_Pressure.png'},
            {name: "Brain",     image: 'icons/Brain.png'},
            {name: "Chemicals",     image: 'icons/Chemicals.png'},
            {name: "Conception",     image: 'icons/Conception.png'},
            {name: "CT_Scan",     image: 'icons/CT_Scan.png'},
            {name: "Dental_Chair",     image: 'icons/Dental_Chair.png'},
            {name: "Dentistry",     image: 'icons/Dentistry.png'},
            {name: "DNA",     image: 'icons/DNA.png'},
            {name: "Donar_List",     image: 'icons/Donar_List.png'},
            {name: "Drinking",     image: 'icons/Drinking.png'},
            {name: "Drinking_and_Smoking",     image: 'icons/Drinking_and_Smoking.png'},
            {name: "Ear",     image: 'icons/Ear.png'},
            {name: "EKG",     image: 'icons/EKG.png'},
            {name: "Emergency_Room",     image: 'icons/Emergency_Room.png'},
            {name: "Eye_Ball",     image: 'icons/Eye_Ball.png'},
            {name: "Eye_Chart",     image: 'icons/Eye_Chart.png'},
            {name: "First_Aid",     image: 'icons/First_Aid.png'},
            {name: "Group_Children",     image: 'icons/Group_Children.png'},
            {name: "Group_Doctors",     image: 'icons/Group_Doctors.png'},
            {name: "Group_Doctors_2",     image: 'icons/Group_Doctors_2.png'},
            {name: "Group_Medical_Team",     image: 'icons/Group_Medical_Team.png'},
            {name: "Group_Patients",     image: 'icons/Group_Patients.png'},
            {name: "Group_Surgical_Team",     image: 'icons/Group_Surgical_Team.png'},
            {name: "Health_Meter",     image: 'icons/Health_Meter.png'},
            {name: "Heart-Orange",     image: 'icons/Heart-Orange.png'},
            {name: "Heart",     image: 'icons/Heart.png'},
            {name: "Heart_Donor",     image: 'icons/Heart_Donor.png'},
            {name: "Herb_Mix",     image: 'icons/Herb_Mix.png'},
            {name: "Hospital",     image: 'icons/Hospital.png'},
            {name: "Hospital_Bed",     image: 'icons/Hospital_Bed.png'},
            {name: "Human_Anatomy",     image: 'icons/Human_Anatomy.png'},
            {name: "ID_Bracelet",     image: 'icons/ID_Bracelet.png'},
            {name: "Inhaler",     image: 'icons/Inhaler.png'},
            {name: "Injury",     image: 'icons/Injury.png'},
            {name: "Insurance_Plan",     image: 'icons/Insurance_Plan.png'},
            {name: "Intestine",     image: 'icons/Intestine.png'},
            {name: "IV_Bag",     image: 'icons/IV_Bag.png'},
            {name: "Labs",     image: 'icons/Labs.png'},
            {name: "Liver",     image: 'icons/Liver.png'},
            {name: "Medical_Bag",     image: 'icons/Medical_Bag.png'},
            {name: "Medical_Database",     image: 'icons/Medical_Database.png'},
            {name: "Medical_Insurance",     image: 'icons/Medical_Insurance.png'},
            {name: "Medical_Invoice",     image: 'icons/Medical_Invoice.png'},
            {name: "Medical_Knowledge_Base",     image: 'icons/Medical_Knowledge_Base.png'},
            {name: "Medical_Office",     image: 'icons/Medical_Office.png'},
            {name: "Medical_Report",     image: 'icons/Medical_Report.png'},
            {name: "Medical_Symbol",     image: 'icons/Medical_Symbol.png'},
            {name: "Medicine_and_Water",     image: 'icons/Medicine_and_Water.png'},
            {name: "Medicine_Liquid",     image: 'icons/Medicine_Liquid.png'},
            {name: "MRI",     image: 'icons/MRI.png'},
            {name: "Pager",     image: 'icons/Pager.png'},
            {name: "Pediatrics",     image: 'icons/Pediatrics.png'},
            {name: "Petri_Dish",     image: 'icons/Petri_Dish.png'},
            {name: "Pharmacy",     image: 'icons/Pharmacy.png'},
            {name: "Pill",     image: 'icons/Pill.png'},
            {name: "Pills",     image: 'icons/Pills.png'},
            {name: "Pills_Strip",     image: 'icons/Pills_Strip.png'},
            {name: "Poison",     image: 'icons/Poison.png'},
            {name: "Pregnant",     image: 'icons/Pregnant.png'},
            {name: "Prescription",     image: 'icons/Prescription.png'},
            {name: "Qualifications",     image: 'icons/Qualifications.png'},
            {name: "Safety_Glasses",     image: 'icons/Safety_Glasses.png'},
            {name: "Safety_Pin",     image: 'icons/Safety_Pin.png'},
            {name: "Sanitation",     image: 'icons/Sanitation.png'},
            {name: "Sanitation_Gloves",     image: 'icons/Sanitation_Gloves.png'},
            {name: "Scalpel",     image: 'icons/Scalpel.png'},
            {name: "Skin",     image: 'icons/Skin.png'},
            {name: "Skull",     image: 'icons/Skull.png'},
            {name: "Smoking",     image: 'icons/Smoking.png'},
            {name: "Sperm",     image: 'icons/Sperm.png'},
            {name: "Stethoscope",     image: 'icons/Stethoscope.png'},
            {name: "Symbol_Admitted",     image: 'icons/Symbol_Admitted.png'},
            {name: "Symbol_Air_Transport",     image: 'icons/Symbol_Air_Transport.png'},
            {name: "Symbol_Discharged",     image: 'icons/Symbol_Discharged.png'},
            {name: "Symbol_Female",     image: 'icons/Symbol_Female.png'},
            {name: "Symbol_Hospital",     image: 'icons/Symbol_Hospital.png'},
            {name: "Symbol_Male",     image: 'icons/Symbol_Male.png'},
            {name: "Symbol_Men",     image: 'icons/Symbol_Men.png'},
            {name: "Symbol_Restrooms",     image: 'icons/Symbol_Restrooms.png'},
            {name: "Symbol_Smoking_Prohibited",     image: 'icons/Symbol_Smoking_Prohibited.png'},
            {name: "Symbol_Transferred",     image: 'icons/Symbol_Transferred.png'},
            {name: "Symbol_Women",     image: 'icons/Symbol_Women.png'},
            {name: "Syringe_and_Vial",     image: 'icons/Syringe_and_Vial.png'},
            {name: "Toddler",     image: 'icons/Toddler.png'},
            {name: "Tooth",     image: 'icons/Tooth.png'},
            {name: "Transfusion",     image: 'icons/Transfusion.png'},
            {name: "Urine_Sample",     image: 'icons/Urine_Sample.png'},
            {name: "User_Baby_Boy",     image: 'icons/User_Baby_Boy.png'},
            {name: "User_Baby_Girl",     image: 'icons/User_Baby_Girl.png'},
            {name: "User_Deceased_Female",     image: 'icons/User_Deceased_Female.png'},
            {name: "User_Dentist",     image: 'icons/User_Dentist.png'},
            {name: "User_Doctor_Female",     image: 'icons/User_Doctor_Female.png'},
            {name: "User_Doctor_Female_2",     image: 'icons/User_Doctor_Female_2.png'},
            {name: "User_Doctor_Male",     image: 'icons/User_Doctor_Male.png'},
            {name: "User_Intensive_Care_Male",     image: 'icons/User_Intensive_Care_Male.png'},
            {name: "User_Intern_Female",     image: 'icons/User_Intern_Female.png'},
            {name: "User_Nurse_Army_Female",     image: 'icons/User_Nurse_Army_Female.png'},
            {name: "User_Nurse_Female",     image: 'icons/User_Nurse_Female.png'},
            {name: "User_Nurse_Female_2",     image: 'icons/User_Nurse_Female_2.png'},
            {name: "User_Patient_Female",     image: 'icons/User_Patient_Female.png'},
            {name: "User_Patient_Male",     image: 'icons/User_Patient_Male.png'},
            {name: "User_Surgeon_Male",     image: 'icons/User_Surgeon_Male.png'},
            {name: "Vial_and_Pills",     image: 'icons/Vial_and_Pills.png'},
            {name: "Virus",     image: 'icons/Virus.png'},
            {name: "Walker",     image: 'icons/Walker.png'},
            {name: "Water",     image: 'icons/Water.png'},
            {name: "Wheel_Chair",     image: 'icons/Wheel_Chair.png'},
            {name: "Xray",     image: 'icons/Xray.png'},
            {name: "Xray_Broken_Bone",     image: 'icons/Xray_Broken_Bone.png'},
            {name: "Xray_Mamography",     image: 'icons/Xray_Mamography.png'},
            {name: "Xray_Tooth",     image: 'icons/Xray_Tooth.png'},
            {name: "Zygote",     image: 'icons/Zygote.png'}

        ];

        for (var i = 0; i < data.length; i++) {
            CategoryIcons.insert({
                name:   data[i].name,
                image:  data[i].image
            });
        }
    }
});
