// if the database is empty on server start, create some sample data.
Meteor.startup(function () {
    if (CategoryIcons.find().count() === 0) {
        var data = [
            {name: "Allergy_Vials",     image: 'iconsbw/Allergy_Vials.png'},
            {name: "Ambulance",     image: 'iconsbw/Ambulance.png'},
            {name: "Baby_Bottle",     image: 'iconsbw/Baby_Bottle.png'},
            {name: "Baby_Carriage",     image: 'iconsbw/Baby_Carriage.png'},
            {name: "Bacteria",     image: 'iconsbw/Bacteria.png'},
            {name: "Band_Aid",     image: 'iconsbw/Band_Aid.png'},
            {name: "Bandage_Roll",     image: 'iconsbw/Bandage_Roll.png'},
            {name: "Blood_Bag",     image: 'iconsbw/Blood_Bag.png'},
            {name: "Blood_Pressure",     image: 'iconsbw/Blood_Pressure.png'},
            {name: "Brain",     image: 'iconsbw/Brain.png'},
            {name: "Chemicals",     image: 'iconsbw/Chemicals.png'},
            {name: "Conception",     image: 'iconsbw/Conception.png'},
            {name: "CT_Scan",     image: 'iconsbw/CT_Scan.png'},
            {name: "Dental_Chair",     image: 'iconsbw/Dental_Chair.png'},
            {name: "Dentistry",     image: 'iconsbw/Dentistry.png'},
            {name: "DNA",     image: 'iconsbw/DNA.png'},
            {name: "Donar_List",     image: 'iconsbw/Donar_List.png'},
            {name: "Drinking",     image: 'iconsbw/Drinking.png'},
            {name: "Drinking_and_Smoking",     image: 'iconsbw/Drinking_and_Smoking.png'},
            {name: "Ear",     image: 'iconsbw/Ear.png'},
            {name: "EKG",     image: 'iconsbw/EKG.png'},
            {name: "Emergency_Room",     image: 'iconsbw/Emergency_Room.png'},
            {name: "Eye_Ball",     image: 'iconsbw/Eye_Ball.png'},
            {name: "Eye_Chart",     image: 'iconsbw/Eye_Chart.png'},
            {name: "First_Aid",     image: 'iconsbw/First_Aid.png'},
            {name: "Group_Children",     image: 'iconsbw/Group_Children.png'},
            {name: "Group_Doctors",     image: 'iconsbw/Group_Doctors.png'},
            {name: "Group_Doctors_2",     image: 'iconsbw/Group_Doctors_2.png'},
            {name: "Group_Medical_Team",     image: 'iconsbw/Group_Medical_Team.png'},
            {name: "Group_Patients",     image: 'iconsbw/Group_Patients.png'},
            {name: "Group_Surgical_Team",     image: 'iconsbw/Group_Surgical_Team.png'},
            {name: "Health_Meter",     image: 'iconsbw/Health_Meter.png'},
            {name: "Heart-Orange",     image: 'iconsbw/Heart-Orange.png'},
            {name: "Heart",     image: 'iconsbw/Heart.png'},
            {name: "Heart_Donor",     image: 'iconsbw/Heart_Donor.png'},
            {name: "Herb_Mix",     image: 'iconsbw/Herb_Mix.png'},
            {name: "Hospital",     image: 'iconsbw/Hospital.png'},
            {name: "Hospital_Bed",     image: 'iconsbw/Hospital_Bed.png'},
            {name: "Human_Anatomy",     image: 'iconsbw/Human_Anatomy.png'},
            {name: "ID_Bracelet",     image: 'iconsbw/ID_Bracelet.png'},
            {name: "Inhaler",     image: 'iconsbw/Inhaler.png'},
            {name: "Injury",     image: 'iconsbw/Injury.png'},
            {name: "Insurance_Plan",     image: 'iconsbw/Insurance_Plan.png'},
            {name: "Intestine",     image: 'iconsbw/Intestine.png'},
            {name: "IV_Bag",     image: 'iconsbw/IV_Bag.png'},
            {name: "Labs",     image: 'iconsbw/Labs.png'},
            {name: "Liver",     image: 'iconsbw/Liver.png'},
            {name: "Medical_Bag",     image: 'iconsbw/Medical_Bag.png'},
            {name: "Medical_Database",     image: 'iconsbw/Medical_Database.png'},
            {name: "Medical_Insurance",     image: 'iconsbw/Medical_Insurance.png'},
            {name: "Medical_Invoice",     image: 'iconsbw/Medical_Invoice.png'},
            {name: "Medical_Knowledge_Base",     image: 'iconsbw/Medical_Knowledge_Base.png'},
            {name: "Medical_Office",     image: 'iconsbw/Medical_Office.png'},
            {name: "Medical_Report",     image: 'iconsbw/Medical_Report.png'},
            {name: "Medical_Symbol",     image: 'iconsbw/Medical_Symbol.png'},
            {name: "Medicine_and_Water",     image: 'iconsbw/Medicine_and_Water.png'},
            {name: "Medicine_Liquid",     image: 'iconsbw/Medicine_Liquid.png'},
            {name: "MRI",     image: 'iconsbw/MRI.png'},
            {name: "Pager",     image: 'iconsbw/Pager.png'},
            {name: "Pediatrics",     image: 'iconsbw/Pediatrics.png'},
            {name: "Petri_Dish",     image: 'iconsbw/Petri_Dish.png'},
            {name: "Pharmacy",     image: 'iconsbw/Pharmacy.png'},
            {name: "Pill",     image: 'iconsbw/Pill.png'},
            {name: "Pills",     image: 'iconsbw/Pills.png'},
            {name: "Pills_Strip",     image: 'iconsbw/Pills_Strip.png'},
            {name: "Poison",     image: 'iconsbw/Poison.png'},
            {name: "Pregnant",     image: 'iconsbw/Pregnant.png'},
            {name: "Prescription",     image: 'iconsbw/Prescription.png'},
            {name: "Qualifications",     image: 'iconsbw/Qualifications.png'},
            {name: "Safety_Glasses",     image: 'iconsbw/Safety_Glasses.png'},
            {name: "Safety_Pin",     image: 'iconsbw/Safety_Pin.png'},
            {name: "Sanitation",     image: 'iconsbw/Sanitation.png'},
            {name: "Sanitation_Gloves",     image: 'iconsbw/Sanitation_Gloves.png'},
            {name: "Scalpel",     image: 'iconsbw/Scalpel.png'},
            {name: "Skin",     image: 'iconsbw/Skin.png'},
            {name: "Skull",     image: 'iconsbw/Skull.png'},
            {name: "Smoking",     image: 'iconsbw/Smoking.png'},
            {name: "Sperm",     image: 'iconsbw/Sperm.png'},
            {name: "Stethoscope",     image: 'iconsbw/Stethoscope.png'},
            {name: "Symbol_Admitted",     image: 'iconsbw/Symbol_Admitted.png'},
            {name: "Symbol_Air_Transport",     image: 'iconsbw/Symbol_Air_Transport.png'},
            {name: "Symbol_Discharged",     image: 'iconsbw/Symbol_Discharged.png'},
            {name: "Symbol_Female",     image: 'iconsbw/Symbol_Female.png'},
            {name: "Symbol_Hospital",     image: 'iconsbw/Symbol_Hospital.png'},
            {name: "Symbol_Male",     image: 'iconsbw/Symbol_Male.png'},
            {name: "Symbol_Men",     image: 'iconsbw/Symbol_Men.png'},
            {name: "Symbol_Restrooms",     image: 'iconsbw/Symbol_Restrooms.png'},
            {name: "Symbol_Smoking_Prohibited",     image: 'iconsbw/Symbol_Smoking_Prohibited.png'},
            {name: "Symbol_Transferred",     image: 'iconsbw/Symbol_Transferred.png'},
            {name: "Symbol_Women",     image: 'iconsbw/Symbol_Women.png'},
            {name: "Syringe_and_Vial",     image: 'iconsbw/Syringe_and_Vial.png'},
            {name: "Toddler",     image: 'iconsbw/Toddler.png'},
            {name: "Tooth",     image: 'iconsbw/Tooth.png'},
            {name: "Transfusion",     image: 'iconsbw/Transfusion.png'},
            {name: "Urine_Sample",     image: 'iconsbw/Urine_Sample.png'},
            {name: "User_Baby_Boy",     image: 'iconsbw/User_Baby_Boy.png'},
            {name: "User_Baby_Girl",     image: 'iconsbw/User_Baby_Girl.png'},
            {name: "User_Deceased_Female",     image: 'iconsbw/User_Deceased_Female.png'},
            {name: "User_Dentist",     image: 'iconsbw/User_Dentist.png'},
            {name: "User_Doctor_Female",     image: 'iconsbw/User_Doctor_Female.png'},
            {name: "User_Doctor_Female_2",     image: 'iconsbw/User_Doctor_Female_2.png'},
            {name: "User_Doctor_Male",     image: 'iconsbw/User_Doctor_Male.png'},
            {name: "User_Intensive_Care_Male",     image: 'iconsbw/User_Intensive_Care_Male.png'},
            {name: "User_Intern_Female",     image: 'iconsbw/User_Intern_Female.png'},
            {name: "User_Nurse_Army_Female",     image: 'iconsbw/User_Nurse_Army_Female.png'},
            {name: "User_Nurse_Female",     image: 'iconsbw/User_Nurse_Female.png'},
            {name: "User_Nurse_Female_2",     image: 'iconsbw/User_Nurse_Female_2.png'},
            {name: "User_Patient_Female",     image: 'iconsbw/User_Patient_Female.png'},
            {name: "User_Patient_Male",     image: 'iconsbw/User_Patient_Male.png'},
            {name: "User_Surgeon_Male",     image: 'iconsbw/User_Surgeon_Male.png'},
            {name: "Vial_and_Pills",     image: 'iconsbw/Vial_and_Pills.png'},
            {name: "Virus",     image: 'iconsbw/Virus.png'},
            {name: "Walker",     image: 'iconsbw/Walker.png'},
            {name: "Water",     image: 'iconsbw/Water.png'},
            {name: "Wheel_Chair",     image: 'iconsbw/Wheel_Chair.png'},
            {name: "Xray",     image: 'iconsbw/Xray.png'},
            {name: "Xray_Broken_Bone",     image: 'iconsbw/Xray_Broken_Bone.png'},
            {name: "Xray_Mamography",     image: 'iconsbw/Xray_Mamography.png'},
            {name: "Xray_Tooth",     image: 'iconsbw/Xray_Tooth.png'},
            {name: "Zygote",     image: 'iconsbw/Zygote.png'}

        ];

        for (var i = 0; i < data.length; i++) {
            CategoryIcons.insert({
                name:   data[i].name,
                image:  data[i].image
            });
        }
    }
});
